/**
 * Standardized error codes
 * Used across all services for consistent error handling
 */

export const ERROR_CODES = {
  // Authentication (AUTH_xxx)
  AUTH_INVALID_CREDENTIALS: 'AUTH_001',
  AUTH_TOKEN_EXPIRED: 'AUTH_002',
  AUTH_INSUFFICIENT_PERMISSIONS: 'AUTH_003',
  AUTH_RATE_LIMIT_EXCEEDED: 'AUTH_004',
  AUTH_2FA_REQUIRED: 'AUTH_005',
  AUTH_2FA_INVALID: 'AUTH_006',
  AUTH_ACCOUNT_LOCKED: 'AUTH_007',
  AUTH_ACCOUNT_INACTIVE: 'AUTH_008',

  // Credit (CREDIT_xxx)
  CREDIT_INSUFFICIENT_AUDITS: 'CREDIT_001',
  CREDIT_INSUFFICIENT_TOKENS: 'CREDIT_002',
  CREDIT_TRIAL_EXPIRED: 'CREDIT_003',
  CREDIT_LIMIT_REACHED: 'CREDIT_004',

  // Instance (INSTANCE_xxx)
  INSTANCE_NOT_FOUND: 'INSTANCE_001',
  INSTANCE_UNHEALTHY: 'INSTANCE_002',
  INSTANCE_SUSPENDED: 'INSTANCE_003',
  INSTANCE_DEPLOYING: 'INSTANCE_004',

  // Deployment (DEPLOY_xxx)
  DEPLOY_SSH_CONNECTION_FAILED: 'DEPLOY_001',
  DEPLOY_SSH_AUTH_FAILED: 'DEPLOY_002',
  DEPLOY_UPLOAD_FAILED: 'DEPLOY_003',
  DEPLOY_INSTALLATION_FAILED: 'DEPLOY_004',
  DEPLOY_HEALTH_CHECK_FAILED: 'DEPLOY_005',
  DEPLOY_ROLLBACK_FAILED: 'DEPLOY_006',

  // AI (AI_xxx)
  AI_SERVICE_UNAVAILABLE: 'AI_001',
  AI_AUDIO_TOO_LARGE: 'AI_002',
  AI_INVALID_AUDIO_FORMAT: 'AI_003',
  AI_PROCESSING_FAILED: 'AI_004',
  AI_QUOTA_EXCEEDED: 'AI_005',

  // Validation (VALIDATION_xxx)
  VALIDATION_FAILED: 'VALIDATION_001',
  VALIDATION_REQUIRED_FIELD: 'VALIDATION_002',
  VALIDATION_INVALID_FORMAT: 'VALIDATION_003',

  // Resource (RESOURCE_xxx)
  RESOURCE_NOT_FOUND: 'RESOURCE_001',
  RESOURCE_ALREADY_EXISTS: 'RESOURCE_002',
  RESOURCE_CONFLICT: 'RESOURCE_003',

  // General (GENERAL_xxx)
  GENERAL_INTERNAL_ERROR: 'GENERAL_001',
  GENERAL_SERVICE_UNAVAILABLE: 'GENERAL_002',
  GENERAL_TIMEOUT: 'GENERAL_003',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];

/**
 * Error code to HTTP status mapping
 */
export const ERROR_HTTP_STATUS: Record<ErrorCode, number> = {
  [ERROR_CODES.AUTH_INVALID_CREDENTIALS]: 401,
  [ERROR_CODES.AUTH_TOKEN_EXPIRED]: 401,
  [ERROR_CODES.AUTH_INSUFFICIENT_PERMISSIONS]: 403,
  [ERROR_CODES.AUTH_RATE_LIMIT_EXCEEDED]: 429,
  [ERROR_CODES.AUTH_2FA_REQUIRED]: 401,
  [ERROR_CODES.AUTH_2FA_INVALID]: 401,
  [ERROR_CODES.AUTH_ACCOUNT_LOCKED]: 403,
  [ERROR_CODES.AUTH_ACCOUNT_INACTIVE]: 403,

  [ERROR_CODES.CREDIT_INSUFFICIENT_AUDITS]: 402,
  [ERROR_CODES.CREDIT_INSUFFICIENT_TOKENS]: 402,
  [ERROR_CODES.CREDIT_TRIAL_EXPIRED]: 402,
  [ERROR_CODES.CREDIT_LIMIT_REACHED]: 402,

  [ERROR_CODES.INSTANCE_NOT_FOUND]: 404,
  [ERROR_CODES.INSTANCE_UNHEALTHY]: 503,
  [ERROR_CODES.INSTANCE_SUSPENDED]: 403,
  [ERROR_CODES.INSTANCE_DEPLOYING]: 409,

  [ERROR_CODES.DEPLOY_SSH_CONNECTION_FAILED]: 500,
  [ERROR_CODES.DEPLOY_SSH_AUTH_FAILED]: 500,
  [ERROR_CODES.DEPLOY_UPLOAD_FAILED]: 500,
  [ERROR_CODES.DEPLOY_INSTALLATION_FAILED]: 500,
  [ERROR_CODES.DEPLOY_HEALTH_CHECK_FAILED]: 500,
  [ERROR_CODES.DEPLOY_ROLLBACK_FAILED]: 500,

  [ERROR_CODES.AI_SERVICE_UNAVAILABLE]: 503,
  [ERROR_CODES.AI_AUDIO_TOO_LARGE]: 413,
  [ERROR_CODES.AI_INVALID_AUDIO_FORMAT]: 400,
  [ERROR_CODES.AI_PROCESSING_FAILED]: 500,
  [ERROR_CODES.AI_QUOTA_EXCEEDED]: 429,

  [ERROR_CODES.VALIDATION_FAILED]: 400,
  [ERROR_CODES.VALIDATION_REQUIRED_FIELD]: 400,
  [ERROR_CODES.VALIDATION_INVALID_FORMAT]: 400,

  [ERROR_CODES.RESOURCE_NOT_FOUND]: 404,
  [ERROR_CODES.RESOURCE_ALREADY_EXISTS]: 409,
  [ERROR_CODES.RESOURCE_CONFLICT]: 409,

  [ERROR_CODES.GENERAL_INTERNAL_ERROR]: 500,
  [ERROR_CODES.GENERAL_SERVICE_UNAVAILABLE]: 503,
  [ERROR_CODES.GENERAL_TIMEOUT]: 504,
};

/**
 * Error code to user-friendly message mapping
 */
export const ERROR_MESSAGES: Record<ErrorCode, string> = {
  [ERROR_CODES.AUTH_INVALID_CREDENTIALS]: 'Invalid username or password',
  [ERROR_CODES.AUTH_TOKEN_EXPIRED]: 'Your session has expired. Please login again',
  [ERROR_CODES.AUTH_INSUFFICIENT_PERMISSIONS]: 'You do not have permission to perform this action',
  [ERROR_CODES.AUTH_RATE_LIMIT_EXCEEDED]: 'Too many requests. Please try again later',
  [ERROR_CODES.AUTH_2FA_REQUIRED]: 'Two-factor authentication is required',
  [ERROR_CODES.AUTH_2FA_INVALID]: 'Invalid verification code',
  [ERROR_CODES.AUTH_ACCOUNT_LOCKED]: 'Your account has been locked. Contact support',
  [ERROR_CODES.AUTH_ACCOUNT_INACTIVE]: 'Your account is inactive. Contact admin',

  [ERROR_CODES.CREDIT_INSUFFICIENT_AUDITS]: 'Audit limit reached. Contact admin',
  [ERROR_CODES.CREDIT_INSUFFICIENT_TOKENS]: 'Token limit reached. Contact admin',
  [ERROR_CODES.CREDIT_TRIAL_EXPIRED]: 'Trial period has expired. Contact admin',
  [ERROR_CODES.CREDIT_LIMIT_REACHED]: 'Usage limit reached. Contact admin',

  [ERROR_CODES.INSTANCE_NOT_FOUND]: 'Instance not found',
  [ERROR_CODES.INSTANCE_UNHEALTHY]: 'Instance is currently unavailable',
  [ERROR_CODES.INSTANCE_SUSPENDED]: 'Instance has been suspended',
  [ERROR_CODES.INSTANCE_DEPLOYING]: 'Instance is being deployed. Please wait',

  [ERROR_CODES.DEPLOY_SSH_CONNECTION_FAILED]: 'Failed to connect to server',
  [ERROR_CODES.DEPLOY_SSH_AUTH_FAILED]: 'Server authentication failed',
  [ERROR_CODES.DEPLOY_UPLOAD_FAILED]: 'Failed to upload deployment package',
  [ERROR_CODES.DEPLOY_INSTALLATION_FAILED]: 'Installation failed',
  [ERROR_CODES.DEPLOY_HEALTH_CHECK_FAILED]: 'Health check failed after deployment',
  [ERROR_CODES.DEPLOY_ROLLBACK_FAILED]: 'Rollback failed',

  [ERROR_CODES.AI_SERVICE_UNAVAILABLE]: 'AI service is temporarily unavailable',
  [ERROR_CODES.AI_AUDIO_TOO_LARGE]: 'Audio file is too large',
  [ERROR_CODES.AI_INVALID_AUDIO_FORMAT]: 'Invalid audio format',
  [ERROR_CODES.AI_PROCESSING_FAILED]: 'AI processing failed',
  [ERROR_CODES.AI_QUOTA_EXCEEDED]: 'AI quota exceeded',

  [ERROR_CODES.VALIDATION_FAILED]: 'Validation failed',
  [ERROR_CODES.VALIDATION_REQUIRED_FIELD]: 'Required field is missing',
  [ERROR_CODES.VALIDATION_INVALID_FORMAT]: 'Invalid format',

  [ERROR_CODES.RESOURCE_NOT_FOUND]: 'Resource not found',
  [ERROR_CODES.RESOURCE_ALREADY_EXISTS]: 'Resource already exists',
  [ERROR_CODES.RESOURCE_CONFLICT]: 'Resource conflict',

  [ERROR_CODES.GENERAL_INTERNAL_ERROR]: 'An unexpected error occurred',
  [ERROR_CODES.GENERAL_SERVICE_UNAVAILABLE]: 'Service is temporarily unavailable',
  [ERROR_CODES.GENERAL_TIMEOUT]: 'Request timed out',
};
